# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A matrix multiplication function written by RCpp to accelerate computation.
#' @param matrixA A matrix
#' @param matrixB Another matrix
#'
#' @return the matrix multiplication of A and B
#'
#' @export
matmult <- function(A, B) {
    .Call(`_spMGM_matmult`, A, B)
}

